* Contributing to Chorebot
** Setting up your development environment

You'll need to be able to compile Haskell code and also download and
compile all of Chorebot's dependencies.

The easiest way to get started is to use Stack:

https://docs.haskellstack.org/en/stable/README/#how-to-install

In the Chorebot repository, you can then run:

#+begin_src sh
stack build
#+end_src

It will take a while the first time you do this, to download and
compile all of Chorebot's dependencies.

** Making a change

Easy: use Github to fork the Chorebot repository, make a new branch,
push up your changes, and open a pull request. Make sure it compiles
first!

** Testing

It's good to write tests for changes if you can. See the existing
tests under =spec/= for examples.

When you open a pull request, tests are run automatically at
[[https://travis-ci.org/mjhoy/chorebot][travis-ci.org]]. While you are making changes, it is good to run:

#+begin_src sh
stack test
#+end_src

as you go, to see if you caused any test failures. Before you send the
pull request, run

#+begin_src sh
stack test --pedantic
#+end_src

to make sure you catch and fix all GHC warnings. I won't accept any
code that is not passing this!

If you are not making any changes to code, include "=[ci skip]=" or
"=[skip ci]=" in your commit message.
